### ISSUE TITLE
Should there be a flag when adding a user to an alias for moderator status?

### ISSUE THREAD

**Issue by cjs** [trevore/galias#15]
At this point when a user is added to a group via alias, they are standard users. We have the ability set someone as a moderator, should that be allowed via galias, or just reserved for the GUI.

**Comment by trevore** [comment]
Good idea, I like it.

**Comment by trevore** [comment]
There is now the ability to make someone and owner when you add them as well as promote and demote commands. There is not really a moderator status in the google API.
