### ISSUE TITLE
When listing users of an alias, should moderators be noted somehow?

### ISSUE THREAD

**Issue by cjs** [trevore/galias#16]
This might not make sense for current usage of aliases, but as we migrate Mailman over, it could be.

**Comment by trevore** [comment]
Yes please :)

___________________________
Trevor R. Ellermann
@trevorellermann
K0DMA
GPG Key: https://ellermann.net/trevor-gpg-public-key.asc

On Wed, Apr 15, 2015 at 7:37 PM, Craig Steinberger <notifications@github.com

**Comment by trevore** [comment]
This has now been implemented.
